# Generated by Django 4.2.5 on 2023-11-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipseite.tour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='activation',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='band',
            name='activation',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='activation',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='activation',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='activation',
            field=models.BinaryField(),
        ),
    ]
