# Generated by Django 4.2.5 on 2023-11-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0003_artist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
