# Generated by Django 4.2.5 on 2023-12-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0004_remove_order_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='emplacement',
            field=models.CharField(default='truc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.CharField(default='descri', max_length=50),
            preserve_default=False,
        ),
    ]
