# Generated by Django 4.2.5 on 2023-12-06 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipseite', '0006_festival_name_order_event_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderDate',
        ),
        migrations.AddField(
            model_name='band',
            name='artists',
            field=models.ManyToManyField(to='ipseite.artist'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='nbTickets',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='festival',
            name='artists',
            field=models.ManyToManyField(to='ipseite.artist'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('orderDate', models.DateField(blank=True, null=True)),
                ('orders', models.ManyToManyField(to='ipseite.order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
