# Generated by Django 4.2.5 on 2023-12-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0007_remove_order_orderdate_band_artists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='nbTickets',
        ),
        migrations.AddField(
            model_name='evenement',
            name='tickets',
            field=models.ManyToManyField(to='ipseite.ticket'),
        ),
    ]
