# Generated by Django 4.2.5 on 2023-12-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0008_remove_evenement_nbtickets_evenement_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='slug',
        ),
        migrations.AddField(
            model_name='evenement',
            name='slug',
            field=models.SlugField(default='slug', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(default='slug', max_length=70),
            preserve_default=False,
        ),
    ]
