# Generated by Django 4.2.5 on 2023-12-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0009_remove_artist_slug_evenement_slug_ticket_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='slug',
        ),
    ]
