# Generated by Django 4.2.5 on 2023-12-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0010_remove_ticket_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='tickets',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipseite.evenement'),
            preserve_default=False,
        ),
    ]
