# Generated by Django 4.2.5 on 2023-12-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0012_remove_ticket_event_evenement_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='orderDate',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='orderDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
