# Generated by Django 4.2.5 on 2024-01-11 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0014_remove_order_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='tickets',
        ),
        migrations.AddField(
            model_name='evenement',
            name='nbPlaces',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipseite.evenement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
