# Generated by Django 4.2.5 on 2024-01-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0016_rename_nbplaces_evenement_nbtickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='nbTickets',
            field=models.IntegerField(default=1),
        ),
    ]
