# Generated by Django 4.2.5 on 2024-01-11 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0017_alter_evenement_nbtickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='festival',
            name='finishDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='festival',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
