# Generated by Django 4.2.5 on 2024-01-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0018_alter_concert_date_alter_festival_finishdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='emplacement',
        ),
        migrations.AlterField(
            model_name='evenement',
            name='activation',
            field=models.BinaryField(default=True),
        ),
    ]
