# Generated by Django 4.2.5 on 2024-01-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0019_remove_ticket_emplacement_alter_evenement_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='activation',
            field=models.BinaryField(),
        ),
    ]
