# Generated by Django 4.2.5 on 2024-01-11 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0020_alter_evenement_activation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=40)),
                ('dateCreation', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
