# Generated by Django 4.2.5 on 2024-01-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0021_emplacement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emplacement',
            old_name='libelle',
            new_name='name',
        ),
    ]
