# Generated by Django 4.2.5 on 2024-01-11 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0022_rename_libelle_emplacement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='emplacement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipseite.emplacement'),
            preserve_default=False,
        ),
    ]
