# Generated by Django 4.2.5 on 2024-02-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0023_ticket_emplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipseite.ticket'),
            preserve_default=False,
        ),
    ]
