# Generated by Django 4.2.5 on 2024-02-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0025_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
    ]
