# Generated by Django 4.2.5 on 2024-02-23 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipseite', '0026_remove_order_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='nbTickets',
        ),
    ]
